CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `estate` (
     `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `title` varchar(50) NOT NULL,
  `excerpt` varchar(200) NOT NULL,
  `description` text NOT NULL,
  `area` int(11) NOT NULL,
  `rooms` int(11) NOT NULL,
  `bedrooms` int(11) NOT NULL,
  `bathrooms` int(11) NOT NULL,
  `parking` tinyint(4) NOT NULL,
  `parking_type` varchar(45) NOT NULL,
  `agent_id` int(11) NOT NULL,
  `outside` tinyint(4) NOT NULL,
  `outside_area` int(11) NOT NULL,
  `floor` int(11) NOT NULL,
  `charge_price` float NOT NULL,
  `price` float NOT NULL,
  `fees` int(11) NOT NULL,
  `available` datetime DEFAULT NULL,
  `building_year` int(11) NOT NULL,
  `zip_code` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `balcony` tinyint(4) NOT NULL,
  `terrace` int(11) NOT NULL,
  `convertible_attic` tinyint(4) NOT NULL,
  `charge_frequency_id` int(11) NOT NULL,
  `status` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_estate_type_idx` (`type_id`),
  KEY `fk_estate_category1_idx` (`category_id`),
  KEY `fk_estate_agent1_idx` (`agent_id`),
  KEY `fk_estate_charge_frequency1_idx` (`charge_frequency_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;